apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  parentRefs:
    - name: gateway-external
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - longhorn.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: longhorn-frontend
        port: 80