# https://projectcontour.io/docs/main/config/api/#projectcontour.io/v1alpha1.ContourDeployment
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-external-params
spec:
  envoy:
    networkPublishing:
      serviceAnnotations:
        metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour-external
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: contour-external-params
    namespace: projectcontour
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour-external
  namespace: projectcontour
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: contour-external
  listeners:
    - name: argocd
      hostname: argocd.haminhchien.id.vn
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        - name: argocd-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
