apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argo
spec:
  parentRefs:
    - name: gateway-external
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - argocd.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: argocd-server
        port: 80