apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/rancher
    repoURL: https://github.com/wermarter/homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true