apiVersion: v2
name: rancher
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: rancher
    repository: https://releases.rancher.com/server-charts/stable
    version: 2.9.3
