apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argo
spec:
  parentRefs:
    - kind: Gateway
      namespace: projectcontour
      name: contour-external
  hostnames:
    - argocd.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: argocd-server
        port: 80
