apiVersion: v2
name: minio
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 14.8.5
