apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio
  namespace: minio
spec:
  parentRefs:
    - name: gateway-external
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - minio.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: minio
        port: 9001