apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  parentRefs:
    - name: gateway-external
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - rabbitmq.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: rabbitmq
        port: 15672