apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rancher
  namespace: cattle-system
spec:
  parentRefs:
    - name: gateway-external
      namespace: envoy-gateway-system
      kind: Gateway
  hostnames:
    - rancher.haminhchien.id.vn
  rules:
    - backendRefs:
      - name: rancher
        port: 80
      filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
          - name: "Host"
            value: "rancher.haminhchien.id.vn"
          - name: "X-Forwarded-Proto"
            value: "https"
          - name: "X-Forwarded-Port"
            value: "443"
          - name: "X-Forwarded-For"
            value: "203.0.113.195"
