- name: "Some other tools"
  hosts: "*"
  tasks:
    - name: Install ripgrep
      become: true
      ansible.builtin.package:
        state: present
        name: ripgrep
    - name: Install unzip
      become: true
      ansible.builtin.package:
        state: present
        name: unzip
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      become: true
      ansible.builtin.shell: |
        swapoff -a
      changed_when: false
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      become: true
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
