apiVersion: v2
name: rabbitmq
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 15.0.6
