rabbitmq:
  replicaCount: 3
  podManagementPolicy: Parallel
  persistence:
    storageClass: none-replicated
  fullnameOverride: rabbitmq
  resourcesPreset: 'none'
  resources:
    requests:
      cpu: 1.5
    limits:
      cpu: 2
  auth:
    username: community-crawler
    existingPasswordSecret: rabbitmq-setup-secret
  communityPlugins: 'https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez'
  extraPlugins: 'rabbitmq_delayed_message_exchange rabbitmq_stream'
  startupProbe:
    enabled: true
    failureThreshold: 30
  readinessProbe:
    failureThreshold: 30
  livenessProbe:
    failureThreshold: 30
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
    prometheusRule:
      enabled: true
  volumePermissions:
    enabled: true
  extraConfiguration: |-
    mnesia_table_loading_retry_timeout = 1200000
